api/package-lock.json
api/package.json
api/src/app.module.ts
api/src/chat/chat.controller.spec.ts
api/src/chat/chat.controller.ts
api/src/config.ts
api/src/middleware.ts
api/src/users/users.controller.ts
database/fixtures/users-fixtures.sql
database/tables.sql
webapp/src/components/menu.tsx
webapp/src/helpers/Helpers.tsx
webapp/src/helpers/Messagerie.tsx
webapp/src/helpers/Users.tsx
webapp/src/index.tsx
webapp/src/pages/Chat.tsx
webapp/src/pages/Home.tsx
webapp/src/pages/Login.tsx
webapp/src/pages/Messagerie.tsx

Pour ne pas faire un trop grosse merge request j'ai divisé en d'autres issues:
* https://github.com/S-Stanley/ft_transcendence/issues/37
* https://github.com/S-Stanley/ft_transcendence/issues/38
* https://github.com/S-Stanley/ft_transcendence/issues/39

19 permettres aux utilisateurs denvoyer des messages privés a dautres users

---

webapp/src/pages/Login/Login.scss
webapp/src/pages/Login/Login.tsx

J'ai un peu changé de login pour passer d'un Fragment à une div et ainsi pouvoir centrer horizontalement ma div. 
Je n'ai pas trouvé de moyen de le faire directement avec le Fragment. 
J'ai crée l'issue #57 pour appliquer le style sur la page alternative login/email une fois que #55 sera merge.

CSS Login page with 42auth

---

api/package-lock.json
api/package.json
api/src/app.module.ts
api/src/configs/userconnected.decorator.ts
api/src/dtos/profile.dto.ts
api/src/entities/user.entity.ts
api/src/middleware.ts
api/src/services/user.service.ts
api/src/users/users.controller.spec.ts
api/src/users/users.controller.ts
database/docker-entrypoint-initdb.d/setup.sh
database/fixtures/users-fixtures.sql
database/functions/login.sql
database/setup.sql
database/tables.sql
docs/secrets.md
webapp/.gitignore
webapp/jest-puppeteer.config.js
webapp/src/components/menu.tsx
webapp/src/config/Config.tsx
webapp/src/helpers/Helpers.tsx
webapp/src/helpers/Messagerie.tsx
webapp/src/helpers/Users.tsx
webapp/src/index.tsx
webapp/src/pages/Home/Home.tsx
webapp/src/pages/Login/EmailLogin.tsx
webapp/src/pages/Login/Login.tsx
webapp/src/pages/chat/Chat.tsx
webapp/tests/login.test.js

1. Fix de l'erreur react quand on va sur la page home
2. Suppression de tous les warning
3. Utilisation des tabulations de 4 spaces partout
4. Ajout d'un .env sur la webapp avec l'uri de redirection et le client id
5. Harmonisation des accolades pour les utilisées au top
6. Documentation sur les secrets
7. Refactor des champs db créer via typeform pour faire utiliser des snake case
8. Remise des fixtures et harmonisation entre typeform et sql
J'ai créer l'issue https://github.com/S-Stanley/ft_transcendence/issues/54 qui sera complementaire a celle-ci.

refactor(webapp,api): refactor fix post #51 - #53

---

api/src/dtos/user42.dto.ts
api/src/entities/user.entity.ts
api/src/services/user.service.ts
database/fixtures/users-fixtures.sql
database/tables.sql

Ajout du champ avatar dans la db. 
Les issues #61 #62 ont été crée pour afficher l'image dans la navbar et la page de profil.

Feat(DB) : Add avatar field in db #59

---

webapp/src/pages/Login/EmailLogin.scss
webapp/src/pages/Login/EmailLogin.tsx
webapp/src/pages/Login/Login.scss
webapp/src/pages/Login/Login.tsx

Add css style for login email page.
Change size of police for login page + remove useless id tag.

fix(webapp) Apply style on email login #57

---

api/src/entities/chatMessahe.entity.ts
api/src/socket.gateway.ts
webapp/src/pages/chat/Chat.tsx

Comme vu a l'oral, on modifie dans cette PR l'id de la socket en utilisant le chat_id

Update socket id messagerie

---

api/src/entities/user.entity.ts
database/tables.sql

Ajout de contrainer sur la db (not null, unique, foreign keys) + un enum
J'ai essayer de faire des tests db avec [pgtap](https://pgtap.org/) mais je n'ai pas réussis a faire le setup :/ peut-etre que j'essayerais dans une autre issue, mais pas tout de suite
Info:
* [contraintes](https://www.postgresql.org/docs/current/ddl-constraints.html)
* [enum](https://www.postgresql.org/docs/current/datatype-enum.html)

feat(database): add unique constraint and foreign key #36

---

.github/workflows/ci.yml
database/docker-entrypoint-initdb.d/setup.sh
database/setup-test.sql
database/tests/test-users.sql
docker-compose.test.yml
scripts/run-db-test.sh

setup de [pgtap](https://pgtap.org/documentation.html) sur le projet pour faire des tests db, on peut le lancer avec scripts/run-db-test.sh et il y a aussi un ajout de ces tests a la ci

feat(database): add pgtap to monorepo with ci #120

---

api/src/app.module.ts
api/src/dtos/matchmaking.dto.ts
api/src/entities/matchmaking.entity.ts
api/src/matchmaking/matchmaking.controller.ts
api/src/services/matchmaking.service.ts
api/src/socket.gateway.ts
database/tables.sql
package-lock.json
webapp/package.json
webapp/src/helpers/Helpers.tsx
webapp/src/helpers/Matchmaking.tsx
webapp/src/index.tsx
webapp/src/interfaces/mathmaking.tsx
webapp/src/pages/Matchmaking/Matchmaking.tsx
webapp/src/pages/Online/Online.scss
webapp/src/pages/Online/Online.tsx
webapp/src/pages/Online/components/Ball.js
webapp/src/pages/Online/components/End.tsx
webapp/src/pages/Online/components/Paddle.js
webapp/src/pages/Online/components/Pong.scss
webapp/src/pages/Online/components/Pong.tsx
webapp/src/pages/Online/styles.css
webapp/src/pages/Play/index.tsx
yarn.lock

Cette PR implemente le systeme de matchmaking ainsi que le debut du jeux en multjoueur, je le fais par etape parce que le jeux va pas mal changer donc c'est mieux de separer les deux, cette pr se concentre surtout sur le systeme de matchmaking
Pour se faire: 
- un nouveau bouton, matchmaking, sur le path /play
- une fois sur le menu matchmaking, deux boutons: un pour trouver un joueur, l'autre pour voir les demandes de partie via console.log (ce-dernier sera supprime mais c'est pour permettre de mieux comprendre ce qu'il se passe sur la db)
- quand on appuie sur 'find opponent', creation d'un element dans la table matchmaking de la db avec l'id du joueur SEULEMENT SI il ny a pas d'autres joueurs qui cherchent une partie. Dans le cas contraire, la partie se lance et la demande est supprime …

67 allow pong to be played in multiplayer

---

api/src/app.module.ts
api/src/entities/friendrequest.entity.ts
api/src/friendrequest/friendrequest.controller.ts
api/src/services/friend_request.service.ts
api/src/services/user.service.ts
database/tables.sql
webapp/src/helpers/Friends.tsx
webapp/src/helpers/Helpers.tsx
webapp/src/helpers/Users.tsx
webapp/src/pages/Friends/FriendSearch.tsx
webapp/src/pages/Friends/customer/friend-requests.js
webapp/src/pages/Profile/Profile.scss
webapp/src/pages/Profile/Profile.tsx

La PR étant un peu grosse j'ai essayé au maximum de diviser ça en plusieurs commits :
- Création de l'entité typeorm `FriendRequest` et de la table sql correspondante
- Ajout du service `FriendRequest` et de son controller pour exécuter des actions ou récupérer des infos sur les friend requests, et nouvelle route `/friends`
- Ajout du helper `Friends` regroupant les méthodes associées aux friend requests
- Ajout de boutons sur la page de profil variant selon le statut de la requête
- Affichage et gestion de toutes les demandes d'ami reçues sur la page `FriendSearch`

Friend requests

---

api/src/socket.gateway.ts
package-lock.json
webapp/src/pages/Matchmaking/Matchmaking.tsx
webapp/src/pages/Online/Online.tsx
webapp/src/pages/Online/components/Ball.js
webapp/src/pages/Online/components/End.tsx
webapp/src/pages/Online/components/Pong.tsx
webapp/src/pages/Pong/Game.tsx
yarn.lock

hello la team, petite pr plutot facile a review, c'est sur le multi du jeux, verifier que tout est fonctionnel mais normalement c'est bon 
En gros: 
- dans la pr d'avant on pouvait bouger les raquettes grace aux websockets, c'est la meme chose cette fois avec la balle :)
- donc il y a un hote qui se charge d'update la position de la balle, et l'autre joueur recois les coordonnees a chaque fois qu'elle change
- j'ai augmente la velocite de la balle parce que les websockets la ralentissait (vu quil y a envoie et reception a chaque update maintenant), ca change rien sur le papier c'est toujours smooth 
- une nouvelle channel de websocket est creee, qui permet d'envoyer et de recevoir la position de la balle
- le cote du joueur est toujours la meme, c'est a dire qu'elle est a gauche pour un …

129 multiplayer game

---

api/src/chat/chat.controller.ts
api/src/entities/chat.entity.ts
database/fixtures/messagerie-fixtures.sql
database/tables.sql
webapp/src/index.tsx
webapp/src/interfaces/messagerie.tsx
webapp/src/pages/Friends/FriendSearch.tsx
webapp/src/pages/Home/Home.tsx
webapp/src/pages/Online/components/Pong.scss
webapp/src/pages/Play/index.tsx
webapp/src/pages/Pong/Game.tsx
webapp/src/pages/Pong/components/Ball.js
webapp/src/pages/Pong/components/Pong.scss
webapp/src/pages/Pong/components/Pong.tsx
webapp/src/pages/Profile/Profile.tsx
webapp/src/pages/TwoFactor/TwoFactorAuth.tsx
webapp/src/pages/TwoFactor/TwoFactorSetUp.tsx
webapp/src/pages/User/Account.tsx
webapp/src/pages/Utils/NewAppBar.tsx
webapp/src/pages/chat/Chat.tsx
webapp/src/pages/messagerie/Messagerie.tsx

Le premier commit est lié a https://github.com/S-Stanley/ft_transcendence/pull/133, seul le 2e commit est a review
Il faut merge cette PR **APRES** celle-ci: https://github.com/S-Stanley/ft_transcendence/pull/133

Add private chat to list

---

webapp/src/index.tsx
webapp/src/pages/Friends/FriendSearch.tsx
webapp/src/pages/Home/Home.tsx
webapp/src/pages/Online/components/Pong.scss
webapp/src/pages/Play/index.tsx
webapp/src/pages/Pong/Game.tsx
webapp/src/pages/Pong/components/Ball.js
webapp/src/pages/Pong/components/Pong.scss
webapp/src/pages/Pong/components/Pong.tsx
webapp/src/pages/Profile/Profile.tsx
webapp/src/pages/TwoFactor/TwoFactorAuth.tsx
webapp/src/pages/TwoFactor/TwoFactorSetUp.tsx
webapp/src/pages/User/Account.tsx
webapp/src/pages/Utils/NewAppBar.tsx
webapp/src/pages/chat/Chat.tsx
webapp/src/pages/messagerie/Messagerie.tsx

* la navbar et le drawer sont desormais declarer une seule fois
* J'ai delete les Box en corrigant le probleme de margin de la navbar, ce qui a retire la background gris qu'on avait sur la moitie de la page, je trouve perso que c'est mieux comme ca
* J'ai retiré le background du pong aussi, il etait dupliqué sur toutes les pages, je pense qu'on fera autrement pour update le terrain

refactor(webapp): use only one navbar and update design !133

---

api/src/chat/chat.controller.ts
webapp/src/interfaces/messagerie.tsx
webapp/src/pages/messagerie/Messagerie.tsx

page concernée: http://localhost:3000/messagerie

136 ajout de la photo de profil des users dans la messagerie

---

api/src/app.module.ts
api/src/chat/chat.controller.ts
database/functions/create_new_chat.sql
database/setup-test.sql
database/setup.sql
database/tables.sql
webapp/src/helpers/Messagerie.tsx
webapp/src/pages/messagerie/Messagerie.scss
webapp/src/pages/messagerie/Messagerie.tsx

L'objectif de cette PR est de permettre de créer un chat public, il y a aussi une table `chat_admin` qui permet de stocker les admin d'un chat (il peut y en avoir plusieurs).
C'est la premier de plusieurs issues que j'ai crée suite a celle-ci (pour terminé 'issue de base):
* https://github.com/S-Stanley/ft_transcendence/issues/148
* https://github.com/S-Stanley/ft_transcendence/issues/149
* https://github.com/S-Stanley/ft_transcendence/issues/150
* https://github.com/S-Stanley/ft_transcendence/issues/151

feat(database,api,webapp): allow any user to create a public chat #20

---

api/src/chat/chat.controller.ts
database/functions/update_chat_admin.sql
database/setup-test.sql
database/setup.sql
webapp/src/helpers/Messagerie.tsx
webapp/src/pages/chat/Settings.tsx

Il faut aller dans les settings pour trouver la feature

149 permettre a un admin dun chat public de set dautres membres comme admin

---

api/src/friendrequest/friendrequest.controller.ts
api/src/middleware.ts
api/src/services/friend_request.service.ts
webapp/src/helpers/Friends.tsx
webapp/src/pages/Friends/FriendSearch.tsx
webapp/src/pages/Friends/customer/friend-requests-sent.js
webapp/src/pages/Profile/Profile.tsx

Ajout des demandes d'ami envoyées par l'utilisateur sur la page Friends avec la possibilité de les annuler, on a réutilisé avec @Anysiia le même principe que pour la liste des demandes d'ami reçues

157 Afficher la liste des demandes d'ami envoyées

---

api/src/chat/chat.controller.ts
api/src/dtos/profile.dto.ts
api/src/entities/blockedUsers.ts
api/src/friendrequest/friendrequest.controller.ts
api/src/services/user.service.ts
api/src/socket.gateway.ts
api/src/users/users.controller.ts
database/functions/create_or_get_chat_id.sql
database/tables.sql
webapp/cypress/e2e/private-chat.cy.js
webapp/src/helpers/Friends.tsx
webapp/src/helpers/Messagerie.tsx
webapp/src/helpers/Users.tsx
webapp/src/interfaces/Chat.tsx
webapp/src/interfaces/user.tsx
webapp/src/pages/Friends/FriendSearch.tsx
webapp/src/pages/Login/Login.tsx
webapp/src/pages/Profile/Profile.tsx
webapp/src/pages/Utils/NewAppBar.tsx
webapp/src/pages/Utils/listItems.tsx
webapp/src/pages/chat/Chat.scss
webapp/src/pages/chat/Chat.tsx
webapp/src/pages/messagerie/Messagerie.tsx

J'ai utilisé https://www.npmjs.com/package/chat-ui-react pour update le design. Malheureusement il y a des choses qui ne fonctionnent pas avec l'outils, par exemple on ne peux pas mettre d'avatar quand on envoie un message, il faut recharger la page, et le bouton "send" est un peu nul. Ceci dit on pourra toujours mettre notre propre text-input a l'avenir si il le faut
A merge apres https://github.com/S-Stanley/ft_transcendence/pull/164

142 afficher les photos de profils des utilisateurs dans le chat

---

api/src/chat/chat.controller.ts
api/src/socket.gateway.ts
package-lock.json
webapp/Dockerfile
webapp/Dockerfile.prod
webapp/cypress/e2e/private-chat.cy.js
webapp/package.json
webapp/src/helpers/Messagerie.tsx
webapp/src/pages/chat/Chat.tsx
webapp/src/pages/messagerie/Messagerie.tsx
yarn.lock

A merge apres https://github.com/S-Stanley/ft_transcendence/pull/166
Pour tester se rendre sur la page de messagerie, cliquer sur les 3 petits points, si l'utilisateur est le seul admin il ne peut pas quitter, sinon oui

150 permettre a un utilisateur de quitter un chat public

---

webapp/src/helpers/Friends.tsx
webapp/src/pages/Friends/customer/friend-list.js
webapp/src/pages/Friends/customer/friend-requests-sent.js
webapp/src/pages/Friends/customer/friend-requests.js

Les requests s'update maintenant individuellement tandis qu'avant lorsqu'on choisissait de refuser, accepter, cancel une demande, elles se mettaient toutes à jour pareil, seulement côté front.
PS: La branche part de la PR d' @Anysiia, si ça pose un pb je peux faire autrement

Fix requests update

---

webapp/package.json
webapp/src/pages/Matchmaking/PrivateGame.tsx
webapp/src/pages/Play/index.tsx
webapp/src/pages/Utils/NewAppBar.tsx
webapp/src/pages/chat/Chat.scss
webapp/src/pages/chat/Chat.tsx
yarn.lock

⚠️ PENSER A FAIRE UN YARN/NPM INSTALL ⚠️ 
L'objectif de cette PR est de gerer le chat pour que @automaths puisse gérer les parties a invitation.
Pour tester:
* Aller dans le sous-menu play (http://localhost:3000/play)
* Cliquer sur "create private game" -> un lien s'est copié dans votre presse-papier et une toast se met en place
* Rendez-vous sur un chat (n'importe lequel) et coller le lien -> le message est different
* Si vous cliquez dessus -> il redirige vers une nouvelle page

feat(webapp): add invitation to party in the pong #22

---

api/src/dtos/userauth.ts
api/src/services/user.service.ts
webapp/src/interfaces/user.tsx
webapp/src/pages/Login/Login.tsx

Solution pour ce qui est demandé ci-dessous :

Rediriger l'utilisateur vers la page pour edit son profil en cas de première connexion

---

api/src/chat/chat.controller.ts
api/src/socket.gateway.ts
database/tables.sql
webapp/src/helpers/Messagerie.tsx
webapp/src/pages/chat/Chat.tsx
webapp/src/pages/chat/Settings.tsx
webapp/src/pages/messagerie/Messagerie.tsx

* ban/unban via settings
* sur un compte member d'un chan, reload la [page de messagerie](http://localhost:3000/messagerie), l'user est desormais not-member et ne peux plus rejoindre le channel jusqu'a ce qu'on l'unban

feat(webapp,api,database): allow admin to ban users #180
